version: '3.1'

services:
  nodjs-server:
    image: $DOCKER_METADATA_OUTPUT_TAGS
    ports:
      - 2021:2021
    networks:
      - frontend

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx.key:/etc/nginx/ssl/nginx.key
    networks:
      - frontend
      
networks:
  frontend:
    driver: bridge
